### ISSUE TITLE
Invisible Bikini bottoms - TAWOBA

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Dungeons-Deviousness#152]
**D&DDC Version**
Beta 6

**Describe the bug**
After rebuilding body as per instructions in the MCM for all 4 DND sets (including bikini), the bikini bottoms are invisible

**To Reproduce**
First time loading after rebuilding for instagram body - invisible (the armour is applied)
>rebuilt second time and checked they had meshes - invisible
>rebuilt for a different body (queen) - still invisible
>deleted TAWOBA from mod list and reran wabbajack, rebuilt body (instagram) - invisble

I accept user error is quite high on the list of probabilities, but this is throwing me. I do this all the time in DND - never seen it with TAWOBA. 

**Expected behavior**
Bikinis are not that small.

**Additional context**
The only other thing I do is import a chargen folder into filesgenerated - basically saved faces. Do not reckon that is causing it. Rest of game is fine, so far.

**Comment by Banzaibear** [comment]
I also installed the downloadable bodyslides - same problem. So now I deleted the whole install + skyrim and will reinstall as I suspect pilot error.

**Comment by ForgottenGlory** [comment]
Fixed Beta 7.

**Comment by Banzaibear** [comment]
Still getting the problem in Beta 7 - TAWOBA bottoms are invisible - almost all other armors are fine (succubus panties only one I have found that clips). Sorry.

**Comment by Eikonoklaste** [comment]
Bikini bottoms are using the same slot as the Bikini tassets (discovered on Iron Bikini Bottom V and Iron Tasset VI)
